/**
 * English and French comments
 * Commentaires anglais et français
 * 
 * This file adds the ACE OA objetcs in the configuration variables of the logistics system.
 * Fichier ajoutant les objets d'ACE OA dans la configuration du système de logistique.
 * 
 * Important note : All the classes names which inherits from the ones used in configuration variables will be also available.
 * Note importante : Tous les noms de classes dérivant de celles utilisées dans les variables de configuration seront aussi valables.
 * 
 * File edited for ACE OA Build 380 (Jul 16 2010)
 * Fichier édité pour ACE OA Build 380 (16 Juil 2010)
 */

// ACE OA est-il présent ? (is ACE OA activated ?)
if (isClass (configFile >> "CfgVehicles" >> "ACE_Required_Logic")) then
{
	/****** TOW WITH VEHICLE / REMORQUER AVEC VEHICULE ******/
	
	/**
	 * List of class names of (ground or air) vehicles which can tow towables objects.
	 * Liste des noms de classes des véhicules terrestres pouvant remorquer des objets remorquables.
	 */
	R3F_LOG_CFG_remorqueurs = R3F_LOG_CFG_remorqueurs +
	[
		"Civcar",
	"Civcarbu",
	"civcarbl",
	"Civcarre",
	"Civcarge",
	"Civcarwh",
	"Civcarsl",
	"Copcar",
	"Copcarhw",
	"Copcarswat",
	"350z",
	"350z_red",
	"350z_kiwi",
	"350z_black",
	"350z_silver",
	"350z_green",
	"350z_blue",
	"350z_gold",
	"350z_white",
	"350z_pink",
	"350z_mod",
	"350z_ruben",
	"350z_v",
	"350z_city",
	"350z_yellow",
	"350z_black_DZ",
	"350z_blue_DZ",
	"350z_green_DZ",
	"350z_kiwi_DZ",
	"350z_pink_DZ",
	"350z_white_DZ",
	"350z_yellow_DZ",
	"350z_cream_DZ",
	"Civcar_DZ",
	"civcarbl_DZ",
	"Civcarbu_DZ",
	"Civcarge_DZ",
	"Civcarre_DZ",
	"Civcarsl_DZ",
	"Civcarwh_DZ",
	"CPD_DZ",
	"CPD_U_DZ",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"baf_atv_d",
	"baf_atv_w",
	"baf_offroad_d",
	"baf_offroad_w",
	"car_hatchback",
	"car_sedan",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc"
	];
	
	/**
	 * List of class names of towables objects.
	 * Liste des noms de classes des objets remorquables.
	 */
	R3F_LOG_CFG_objets_remorquables = R3F_LOG_CFG_objets_remorquables +
	[
		"Civcar",
	"Civcarbu",
	"civcarbl",
	"Civcarre",
	"Civcarge",
	"Civcarwh",
	"Civcarsl",
	"Copcar",
	"Copcarhw",
	"Copcarswat",
	"350z",
	"350z_red",
	"350z_kiwi",
	"350z_black",
	"350z_silver",
	"350z_green",
	"350z_blue",
	"350z_gold",
	"350z_white",
	"350z_pink",
	"350z_mod",
	"350z_ruben",
	"350z_v",
	"350z_city",
	"350z_yellow",
	"350z_black_DZ",
	"350z_blue_DZ",
	"350z_green_DZ",
	"350z_kiwi_DZ",
	"350z_pink_DZ",
	"350z_white_DZ",
	"350z_yellow_DZ",
	"350z_cream_DZ",
	"Civcar_DZ",
	"civcarbl_DZ",
	"Civcarbu_DZ",
	"Civcarge_DZ",
	"Civcarre_DZ",
	"Civcarsl_DZ",
	"Civcarwh_DZ",
	"CPD_DZ",
	"CPD_U_DZ",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"baf_atv_d",
	"baf_atv_w",
	"baf_offroad_d",
	"baf_offroad_w",
	"car_hatchback",
	"car_sedan",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc"
	];
	
	
	/****** LIFT WITH VEHICLE / HELIPORTER AVEC VEHICULE ******/
	
	/**
	 * List of class names of air vehicles which can lift liftables objects.
	 * Liste des noms de classes des véhicules aériens pouvant héliporter des objets héliportables.
	 */
	R3F_LOG_CFG_heliporteurs = R3F_LOG_CFG_heliporteurs +
	[
	"ah64d_ep1",
	"baf_merlin_dze",
	"ch53_dze",
	"ch_47f_baf",
	"ch_47f_ep1",
	"ch_47f_ep1_dz",
	"ch_47f_ep1_dze",
	"m6_ep1",
	"mi17_civilian_dz",
	"mi17_dze",
	"mq9predatorb_us_ep1",
	"uh1h_dze",
	"uh1h_tk_ep1",
	"uh1y",
	"uh1y_dze",
	"uh60m_ep1_dze"
	];
	
	/**
	 * List of class names of liftables objects.
	 * Liste des noms de classes des objets héliportables.
	 */
	R3F_LOG_CFG_objets_heliportables = R3F_LOG_CFG_objets_heliportables +
	[
	"Civcar",
	"Civcarbu",
	"civcarbl",
	"Civcarre",
	"Civcarge",
	"Civcarwh",
	"Civcarsl",
	"Copcar",
	"Copcarhw",
	"Copcarswat",
	"350z",
	"350z_red",
	"350z_kiwi",
	"350z_black",
	"350z_silver",
	"350z_green",
	"350z_blue",
	"350z_gold",
	"350z_white",
	"350z_pink",
	"350z_mod",
	"350z_ruben",
	"350z_v",
	"350z_city",
	"350z_yellow",
	"350z_black_DZ",
	"350z_blue_DZ",
	"350z_green_DZ",
	"350z_kiwi_DZ",
	"350z_pink_DZ",
	"350z_white_DZ",
	"350z_yellow_DZ",
	"350z_cream_DZ",
	"Civcar_DZ",
	"civcarbl_DZ",
	"Civcarbu_DZ",
	"Civcarge_DZ",
	"Civcarre_DZ",
	"Civcarsl_DZ",
	"Civcarwh_DZ",
	"CPD_DZ",
	"CPD_U_DZ",
	"armoredsuv_pmc",
	"armoredsuv_pmc_dz",
	"armoredsuv_pmc_dze",
	"atv_cz_ep1",
	"atv_us_ep1",
	"baf_atv_d",
	"baf_atv_w",
	"baf_offroad_d",
	"baf_offroad_w",
	"car_hatchback",
	"car_sedan",
	"datsun1_civil_1_open",
	"datsun1_civil_2_covered",
	"datsun1_civil_3_open",
	"fishing_boat",
	"gaz_vodnik",
	"gaz_vodnik_dz",
	"gaz_vodnik_dz_lm",
	"gaz_vodnik_dz_vlm",
	"gaz_vodnik_dze",
	"gaz_vodnik_hmg",
	"gaz_vodnik_medevac",
	"glt_m300_lt",
	"glt_m300_st",
	"hilux1_civil_1_open",
	"hilux1_civil_2_covered",
	"hilux1_civil_3_open",
	"hilux1_civil_3_open_ep1",
	"hmmwv",
	"hmmwv_ambulance",
	"hmmwv_ambulance_cz_des_ep1",
	"hmmwv_ambulance_des_ep1",
	"hmmwv_armored",
	"hmmwv_avenger",
	"hmmwv_avenger_des_ep1",
	"hmmwv_des_ep1",
	"hmmwv_dz",
	"hmmwv_m1035_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1",
	"hmmwv_m1151_m2_cz_des_ep1_dz",
	"hmmwv_m1151_m2_cz_des_ep1_dze",
	"hmmwv_m1151_m2_des_ep1",
	"hmmwv_m2",
	"hmmwv_m998_crows_m2_des_ep1",
	"hmmwv_m998_crows_mk19_des_ep1",
	"hmmwv_m998a2_sov_des_ep1",
	"hmmwv_m998a2_sov_des_ep1_dz",
	"hmmwv_m998a2_sov_des_ep1_dze",
	"hmmwv_mk19",
	"hmmwv_mk19_des_ep1",
	"hmmwv_terminal_ep1",
	"hmmwv_tow",
	"hmmwv_tow_des_ep1",
	"ikarus",
	"ikarus_tk_civ_ep1",
	"jetskiyanahui_blue",
	"jetskiyanahui_green",
	"jetskiyanahui_red",
	"jetskiyanahui_yellow",
	"kamaz",
	"kamazopen",
	"kamazreammo",
	"kamazrefuel",
	"kamazrefuel_dz",
	"kamazrepair",
	"lada1",
	"lada1_gdr",
	"lada1_tk_civ_ep1",
	"lada2",
	"lada2_gdr",
	"lada2_tk_civ_ep1",
	"lada4_gdr",
	"lada5_gdr",
	"lada_base",
	"ladalm",
	"landrover_cz_ep1",
	"landrover_mg_tk_ep1",
	"landrover_mg_tk_ep1_dz",
	"landrover_mg_tk_ep1_dze",
	"landrover_mg_tk_ins_ep1",
	"landrover_special_cz_ep1",
	"landrover_special_cz_ep1_dz",
	"landrover_special_cz_ep1_dze",
	"landrover_spg9_tk_ep1",
	"landrover_spg9_tk_ins_ep1",
	"landrover_tk_civ_ep1",
	"m1030",
	"m1030_us_des_ep1",
	"m1126_icv_m2_ep1",
	"m1126_icv_mk19_ep1",
	"m1128_mgs_ep1",
	"m1129_mc_ep1",
	"m1130_cv_ep1",
	"m1133_mev_ep1",
	"m1135_atgmv_ep1",
	"m113_tk_ep1",
	"m113_un_ep1",
	"m113ambul_tk_ep1",
	"m113ambul_tk_ep1_dz",
	"m113ambul_un_ep1",
	"m113ambul_un_ep1_dz",
	"mtvr",
	"mtvr_des_ep1",
	"mtvrreammo",
	"mtvrreammo_des_ep1",
	"mtvrrefuel",
	"mtvrrefuel_des_ep1",
	"mtvrrefuel_des_ep1_dz",
	"mtvrrepair",
	"mtvrrepair_des_ep1",
	"mtvrsalvage_des_ep1",
	"mtvrsupply_des_ep1",
	"offroad_dshkm_gue",
	"offroad_dshkm_gue_dz",
	"offroad_dshkm_gue_dze",
	"offroad_dshkm_gue_dze1",
	"offroad_dshkm_gue_dze2",
	"offroad_dshkm_gue_dze3",
	"offroad_dshkm_gue_dze4",
	"offroad_dshkm_ins",
	"offroad_dshkm_tk_gue_ep1",
	"offroad_spg9_gue",
	"offroad_spg9_tk_gue_ep1",
	"old_bike_tk_civ_ep1",
	"old_bike_tk_ins_ep1",
	"old_moto_tk_civ_ep1",
	"papercar",
	"pchela1t",
	"pickup_pk_gue",
	"pickup_pk_gue_dz",
	"pickup_pk_gue_dze",
	"pickup_pk_ins",
	"pickup_pk_ins_dz",
	"pickup_pk_ins_dze",
	"pickup_pk_tk_gue_ep1",
	"pickup_pk_tk_gue_ep1_dz",
	"pickup_pk_tk_gue_ep1_dze",
	"policecar",
	"rhib",
	"rhib2turret",
	"s1203_ambulance_ep1",
	"s1203_tk_civ_ep1",
	"seafox",
	"seafox_ep1",
	"skoda",
	"skodablue",
	"skodagreen",
	"skodared",
	"smallboat_1",
	"smallboat_2",
	"suv_blue",
	"suv_camo",
	"suv_charcoal",
	"suv_dz",
	"suv_green",
	"suv_orange",
	"suv_pink",
	"suv_pmc",
	"suv_pmc_baf",
	"suv_red",
	"suv_silver",
	"suv_tk_civ_ep1",
	"suv_tk_ep1",
	"suv_un_ep1",
	"suv_white",
	"suv_yellow",
	"towingtractor",
	"tractor",
	"tractorold",
	"tt650_civ",
	"tt650_gue",
	"tt650_ins",
	"tt650_tk_civ_ep1",
	"tt650_tk_ep1",
	"uaz_ags30_cdf",
	"uaz_ags30_ins",
	"uaz_ags30_ru",
	"uaz_ags30_tk_ep1",
	"uaz_cdf",
	"uaz_ins",
	"uaz_mg_cdf",
	"uaz_mg_cdf",
	"uaz_mg_cdf_dz_lm",
	"uaz_mg_cdf_dz_vlm",
	"uaz_mg_ins",
	"uaz_mg_ins_dz_lm",
	"uaz_mg_ins_dz_vlm",
	"uaz_mg_tk_ep1",
	"uaz_mg_tk_ep1_dz",
	"uaz_mg_tk_ep1_dze",
	"uaz_ru",
	"uaz_spg9_ins",
	"uaz_unarmed_tk_civ_ep1",
	"uaz_unarmed_tk_ep1",
	"uaz_unarmed_un_ep1",
	"ural_cdf",
	"ural_ins",
	"ural_tk_civ_ep1",
	"ural_un_ep1",
	"ural_zu23_cdf",
	"ural_zu23_gue",
	"ural_zu23_ins",
	"ural_zu23_tk_ep1",
	"ural_zu23_tk_gue_ep1",
	"uralcivil",
	"uralcivil2",
	"uralopen_cdf",
	"uralopen_ins",
	"uralreammo_cdf",
	"uralreammo_ins",
	"uralreammo_tk_ep1",
	"uralrefuel_cdf",
	"uralrefuel_ins",
	"uralrefuel_tk_ep1",
	"uralrefuel_tk_ep1_dz",
	"uralrepair_cdf",
	"uralrepair_ins",
	"uralrepair_tk_ep1",
	"uralsalvage_tk_ep1",
	"uralsupply_tk_ep1",
	"v3s_civ",
	"v3s_gue",
	"v3s_open_tk_civ_ep1",
	"v3s_open_tk_ep1",
	"v3s_reammo_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1",
	"v3s_refuel_tk_gue_ep1_dz",
	"v3s_repair_tk_gue_ep1",
	"v3s_salvage_tk_gue_ep1",
	"v3s_supply_tk_gue_ep1",
	"v3s_tk_ep1",
	"v3s_tk_gue_ep1",
	"volha_1_tk_civ_ep1",
	"volha_2_tk_civ_ep1",
	"volhalimo_tk_civ_ep1",
	"vwgolf",
	"warfarereammotruck_cdf",
	"warfarereammotruck_gue",
	"warfarereammotruck_ins",
	"warfarereammotruck_ru",
	"warfarereammotruck_usmc",
	"warfarerepairtruck_gue",
	"warfaresalvagetruck_cdf",
	"warfaresalvagetruck_gue",
	"warfaresalvagetruck_ins",
	"warfaresalvagetruck_ru",
	"warfaresalvagetruck_usmc",
	"warfaresupplytruck_cdf",
	"warfaresupplytruck_gue",
	"warfaresupplytruck_ins",
	"warfaresupplytruck_ru",
	"warfaresupplytruck_usmc"
	];
	
	
	/****** LOAD IN VEHICLE / CHARGER DANS LE VEHICULE ******/
	
	/*
	 * This section use a quantification of the volume and/or weight of the objets.
	 * The arbitrary referencial used is : an ammo box of type USSpecialWeaponsBox "weights" 5 units.
	 * 
	 * Cette section utilise une quantification du volume et/ou poids des objets.
	 * Le référentiel arbitraire utilisé est : une caisse de munition de type USSpecialWeaponsBox "pèse" 5 unités.
	 * 
	 * Note : the priority of a declaration of capacity to another corresponds to their order in the tables.
	 *   For example : the "Truck" class is in the "Car" class (see http://community.bistudio.com/wiki/ArmA_2:_CfgVehicles).
	 *   If "Truck" is declared with a capacity of 140 before "Car". And if "Car" is declared after "Truck" with a capacity of 40,
	 *   Then all the sub-classes in "Truck" will have a capacity of 140. And all the sub-classes of "Car", excepted the ones
	 *   in "Truck", will have a capacity of 40.
	 * 
	 * Note : la priorité d'une déclaration de capacité sur une autre correspond à leur ordre dans les tableaux.
	 *   Par exemple : la classe "Truck" appartient à la classe "Car" (voir http://community.bistudio.com/wiki/ArmA_2:_CfgVehicles).
	 *   Si "Truck" est déclaré avec une capacité de 140 avant "Car". Et que "Car" est déclaré après "Truck" avec une capacité de 40,
	 *   Alors toutes les sous-classes appartenant à "Truck" auront une capacité de 140. Et toutes les sous-classes appartenant
	 *   à "Car", exceptées celles de "Truck", auront une capacité de 40.
	 */
	
	/**
	 * List of class names of (ground or air) vehicles which can transport transportables objects.
	 * The second element of the arrays is the load capacity (in relation with the capacity cost of the objects).
	 * 
	 * Liste des noms de classes des véhicules (terrestres ou aériens) pouvant transporter des objets transportables.
	 * Le deuxième élément des tableaux est la capacité de chargement (en relation avec le coût de capacité des objets).
	 */
	R3F_LOG_CFG_transporteurs = R3F_LOG_CFG_transporteurs +
	[
	["Civcar",25],
	["Civcarbu", 25],
	["civcarbl", 25],
	["Civcarre", 25],
	["Civcarge", 25],
	["Civcarwh", 25],
	["Civcarsl", 25],
	["Copcar", 50],
	["Copcarhw", 50],
	["Copcarswat", 50],
	["350z", 25],
	["350z_red", 25],
	["350z_kiwi", 25],
	["350z_black", 25],
	["350z_silver", 25],
	["350z_green", 25],
	["350z_blue", 25],
	["350z_gold", 25],
	["350z_white", 25],
	["350z_pink", 25],
	["350z_mod", 25],
	["350z_ruben", 25],
	["350z_v", 25],
	["350z_city", 25],
	["350z_yellow", 25],
	["350z_black_DZ", 25],
	["350z_blue_DZ", 25],
	["350z_green_DZ", 25],
	["350z_kiwi_DZ", 25],
	["350z_pink_DZ", 25],
	["350z_white_DZ", 25],
	["350z_yellow_DZ", 25],
	["350z_cream_DZ", 25],
	["Civcar_DZ", 25],
	["civcarbl_DZ", 25],
	["Civcarbu_DZ", 25],
	["Civcarge_DZ", 25],
	["Civcarre_DZ", 25],
	["Civcarsl_DZ", 25],
	["Civcarwh_DZ", 25],
	["CPD_DZ", 25],
	["CPD_U_DZ", 25],
	["CH_47F_EP1_DZE", 150],
	["Mi17_DZE", 50],
	["Mi24_D_TK_EP1_DZ", 50],
	["Mi17_Civilian_DZ", 50],
	["MTVR_DES_EP1", 50],
	["MTVR", 50],
	["V3S_Open_TK_CIV_EP1", 50],
	["V3S_Open_TK_EP1", 50],
	["Ural_UN_EP1", 50],
	["Ural_TK_CIV_EP1", 50],
	["Ural_CDF", 50],
	["hilux1_civil_1_open", 25],
	["hilux1_civil_2_covered", 25],
	["hilux1_civil_3_open_EP1", 25],
	["datsun1_civil_1_open", 25],
	["datsun1_civil_2_covered", 25],
	["datsun1_civil_3_open", 25],
	["Pickup_PK_TK_GUE_EP1", 25],
	["Pickup_PK_GUE", 25],
	["Pickup_PK_INS", 25],
	["Offroad_DSHKM_Gue", 25],
	["Pickup_PK_GUE", 25],
	["HMMWV_M1151_M2_CZ_DES_EP1_DZE", 25],
	["LandRover_CZ_EP1", 10],
	["LandRover_MG_TK_EP1_DZE", 10],
	["LandRover_Special_CZ_EP1_DZE", 10],
	["LandRover_TK_CIV_EP1", 10],
	["SUV_Green", 40],
	["SUV_Yellow", 40],
	["SUV_White", 40],
	["SUV_Silver", 40],
	["SUV_Red", 40],
	["SUV_Pink", 40],
	["SUV_Orange", 40],
	["SUV_Charcoal", 40],
	["SUV_Blue", 40],
	["ArmoredSUV_PMC_DZE", 40],
	["SUV_Camo", 40],
	["HMMWV_Armored", 100],
	["KamazRefuel_DZ", 50],
	["MtvrRefuel_DES_EP1_DZ", 50],
	["UralRefuel_TK_EP1_DZ", 50],
	["V3S_Refuel_TK_GUE_EP1_DZ", 50],
	["M113Ambul_UN_EP1", 75],
	["M113Ambul_TK_EP1", 75],
	["BRDM2_HQ_Gue", 50],
	["LAV25_HQ", 100],
	["TowingTractor", 25],
	["UH1H_DZE", 75],
	["M1126_ICV_M2_EP1", 100],
	["BAF_Merlin_HC3_D", 100],
	["UH60M_EP1_DZE", 125],
	["BTR40_TK_GUE_EP1", 50],
	["BTR40_TK_INS_EP1", 50],
	["V3S_Reammo_TK_GUE_EP1", 75],
	["V3S_Repair_TK_GUE_EP1", 75],
	["V3S_Salvage_TK_GUE_EP1", 75],
	["MH60S", 75]
	];
	
	/**
	 * List of class names of transportables objects.
	 * The second element of the arrays is the cost capacity (in relation with the capacity of the vehicles).
	 * 
	 * Liste des noms de classes des objets transportables.
	 * Le deuxième élément des tableaux est le coût de capacité (en relation avec la capacité des véhicules).
	 */
	R3F_LOG_CFG_objets_transportables = R3F_LOG_CFG_objets_transportables +
	[
		["RUBasicAmmunitionBox", 5],
		["RUOrdnanceBox", 9],
		["RUVehicleBox", 40],
		["RUBasicWeaponsBox", 15],
		["RULaunchers", 9],
		["RULaunchersBox", 9],
		["RUSpecialWeaponsBox", 15],
		["USBasicAmmunitionBox", 4],
		["USOrdnanceBox", 4],
		["USVehicleBox", 35],
		["USVehicleBox_EP1", 35],
		["USBasicWeaponsBox", 12],
		["USLaunchersBox", 9],
		["SpecialWeaponsBox", 12],
		["USSpecialWeaponsBox", 12],
		["ATV_CZ_EP1", 50],
		["ATV_US_EP1", 50],
		["Old_moto_TK_Civ_EP1", 25],
		["M1030_US_DES_EP1", 25],
		["TT650_Civ", 25],
		["TT650_Ins", 25],
		["TT650_TK_CIV_EP1", 25],
		["MMT_Civ", 25],
		["Old_bike_TK_INS_EP1", 25],
		["Barrels", 15],
		["USVehicleBox_EP1", 10],
		["USSpecialWeaponsBox", 5],
		["TKSpecialWeapons_EP1", 5],
		["BAF_BasicAmmunitionBox", 5],
		["foodbox0", 5]
		
	];
	
	
	/****** MOVABLE-BY-PLAYER OBJECTS / OBJETS DEPLACABLES PAR LE JOUEUR ******/
	
	/**
	 * List of class names of objects moveables by player.
	 * Liste des noms de classes des objets transportables par le joueur.
	 */
	R3F_LOG_CFG_objets_deplacables = R3F_LOG_CFG_objets_deplacables +
	[
		"Barrels",
		"USSpecialWeaponsBox",
		"USVehicleBox_EP1",
		"TKSpecialWeapons_EP1",
		"BAF_BasicAmmunitionBox",
		"foodbox0"
	];
};